/**
 * Seed script — loads products from frontend data into MongoDB.
 * Run: node seed.js
 */
require("dotenv").config();
const mongoose = require("mongoose");
const connectDB = require("./config/db");
const Product = require("./models/Product");

const products = [
  {
    name: "Phantom X Pro Controller",
    price: 79.99,
    originalPrice: 99.99,
    image: "https://upload.wikimedia.org/wikipedia/commons/5/59/DualShock_4.jpg",
    category: "Controllers",
    rating: 4.8,
    description: "Precision gaming controller with haptic feedback and adaptive triggers for the ultimate gaming experience.",
    featured: true,
  },
  {
    name: "DualShock Classic (PS4)",
    price: 59.99,
    originalPrice: 69.99,
    image: "https://upload.wikimedia.org/wikipedia/commons/5/59/DualShock_4.jpg",
    category: "Controllers",
    rating: 4.7,
    description: "Ergonomic PS4 wireless controller with responsive triggers and textured grips.",
    featured: true,
  },
  {
    name: "DualShock 4 Glacier White (PS4)",
    price: 64.99,
    originalPrice: 74.99,
    image: "https://upload.wikimedia.org/wikipedia/commons/5/59/DualShock_4.jpg",
    category: "Controllers",
    rating: 4.6,
    description: "PS4 controller in Glacier White with precision analog sticks and responsive buttons.",
    featured: false,
  },
  {
    name: "DualSense Edge (PS5)",
    price: 199.99,
    originalPrice: null,
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/Playstation_Dualsense_controller.jpg/1280px-Playstation_Dualsense_controller.jpg",
    category: "Controllers",
    rating: 4.9,
    description: "Premium PS5 controller with adaptive triggers, haptics, and customizable profiles.",
    featured: true,
  },
  {
    name: "DualSense Midnight Black (PS5)",
    price: 74.99,
    originalPrice: 84.99,
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/Playstation_Dualsense_controller.jpg/1280px-Playstation_Dualsense_controller.jpg",
    category: "Controllers",
    rating: 4.7,
    description: "PS5 DualSense controller with adaptive triggers, immersive haptics, and a midnight finish.",
    featured: false,
  },
  {
    name: "RetroWave (PS3)",
    price: 39.99,
    originalPrice: null,
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/49/DualShock_3.jpg/1280px-DualShock_3.jpg",
    category: "Controllers",
    rating: 4.5,
    description: "Classic PS3-style controller feel with wireless freedom and long battery life.",
    featured: false,
  },
  {
    name: "DualShock 3 Black (PS3)",
    price: 34.99,
    originalPrice: 44.99,
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/49/DualShock_3.jpg/1280px-DualShock_3.jpg",
    category: "Controllers",
    rating: 4.4,
    description: "Original PS3 DualShock feel with reliable wireless play and classic layout.",
    featured: false,
  },
  {
    name: "DualShock 4 Steel Blue (PS4)",
    price: 64.99,
    originalPrice: 79.99,
    image: "https://upload.wikimedia.org/wikipedia/commons/5/59/DualShock_4.jpg",
    category: "Controllers",
    rating: 4.6,
    description: "Steel Blue PS4 controller with built-in touchpad and improved grips.",
    featured: false,
  },
  {
    name: "DualShock 4 Camouflage (PS4)",
    price: 69.99,
    originalPrice: null,
    image: "https://upload.wikimedia.org/wikipedia/commons/5/59/DualShock_4.jpg",
    category: "Controllers",
    rating: 4.5,
    description: "Camo PS4 wireless controller with refined sticks and responsive triggers.",
    featured: false,
  },
  {
    name: "DualSense Cosmic Red (PS5)",
    price: 79.99,
    originalPrice: 89.99,
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/Playstation_Dualsense_controller.jpg/1280px-Playstation_Dualsense_controller.jpg",
    category: "Controllers",
    rating: 4.8,
    description: "PS5 DualSense in Cosmic Red with adaptive triggers and immersive haptics.",
    featured: false,
  },
  {
    name: "DualSense Starlight Blue (PS5)",
    price: 79.99,
    originalPrice: null,
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/Playstation_Dualsense_controller.jpg/1280px-Playstation_Dualsense_controller.jpg",
    category: "Controllers",
    rating: 4.7,
    description: "Starlight Blue PS5 controller with precision sticks and enhanced grip.",
    featured: false,
  },
  {
    name: "HyperSound Elite Headset",
    price: 149.99,
    originalPrice: null,
    image: "https://images.unsplash.com/photo-1599669454699-248893623440?w=600&q=80",
    category: "Audio",
    rating: 4.9,
    description: "7.1 surround sound gaming headset with noise-cancelling microphone and memory foam ear cushions.",
    featured: true,
  },
  {
    name: "Vortex RGB Mechanical Keyboard",
    price: 129.99,
    originalPrice: 159.99,
    image: "https://images.unsplash.com/photo-1618384887929-16ec33fab9ef?w=600&q=80",
    category: "Keyboards",
    rating: 4.7,
    description: "Cherry MX switches with per-key RGB lighting and aircraft-grade aluminum frame.",
    featured: true,
  },
  {
    name: "NightHawk Gaming Mouse",
    price: 69.99,
    originalPrice: null,
    image: "https://images.unsplash.com/photo-1527814050087-3793815479db?w=600&q=80",
    category: "Mice",
    rating: 4.6,
    description: "25,600 DPI sensor with 8 programmable buttons and ultra-lightweight design.",
  },
  {
    name: "UltraWide Curved Monitor 34\"",
    price: 499.99,
    originalPrice: 599.99,
    image: "https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?w=600&q=80",
    category: "Monitors",
    rating: 4.9,
    description: "WQHD 165Hz curved gaming monitor with 1ms response time and HDR600.",
  },
  {
    name: "StreamDeck Pro",
    price: 199.99,
    originalPrice: null,
    image: "https://images.unsplash.com/photo-1625842268584-8f3296236761?w=600&q=80",
    category: "Accessories",
    rating: 4.5,
    description: "15-key LCD streaming controller for content creators and gamers.",
  },
  {
    name: "Titan Gaming Chair",
    price: 349.99,
    originalPrice: 449.99,
    image: "https://images.unsplash.com/photo-1598550476439-6847785fcea6?w=600&q=80",
    category: "Furniture",
    rating: 4.4,
    description: "Ergonomic gaming chair with 4D armrests, lumbar support, and premium PU leather.",
  },
  {
    name: "RGB Mouse Pad XXL",
    price: 39.99,
    originalPrice: null,
    image: "https://images.unsplash.com/photo-1616788494672-ec7ca25fdda9?w=600&q=80",
    category: "Accessories",
    rating: 4.3,
    description: "Extended mouse pad with 12 RGB lighting modes and micro-textured surface.",
  },
  {
    name: "Apex RTX 5080 GPU",
    price: 1299.99,
    originalPrice: 1399.99,
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/df/Leistungsanalyse_NVIDIA_GeForce_RTX_4090_%28Geekerwan%29_02_cropped.jpg/330px-Leistungsanalyse_NVIDIA_GeForce_RTX_4090_%28Geekerwan%29_02_cropped.jpg",
    category: "GPUs",
    rating: 4.9,
    description: "High-end 4K graphics card with advanced ray tracing and AI frame generation.",
    featured: true,
  },
  {
    name: "Blaze RX 8900 XT GPU",
    price: 1099.99,
    originalPrice: null,
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/48/RTX_3090_Founders_Edition.jpg/330px-RTX_3090_Founders_Edition.jpg",
    category: "GPUs",
    rating: 4.8,
    description: "Ultra-fast gaming GPU designed for high refresh rate AAA performance.",
  },
  {
    name: "TitanCore i9 14900K CPU",
    price: 619.99,
    originalPrice: 679.99,
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Intel_i9-14900KF_CPU.jpg/330px-Intel_i9-14900KF_CPU.jpg",
    category: "CPUs",
    rating: 4.8,
    description: "24-core desktop processor for top gaming and streaming performance.",
  },
  {
    name: "RyzenStorm 9 9950X CPU",
    price: 659.99,
    originalPrice: null,
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/99/Ryzen3pro2100ge-ph-gerald.jpg/330px-Ryzen3pro2100ge-ph-gerald.jpg",
    category: "CPUs",
    rating: 4.9,
    description: "High-clock multi-core processor optimized for gaming and creator workloads.",
  },
  {
    name: "FrostFlow 360 AIO Cooling",
    price: 189.99,
    originalPrice: null,
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/25/AMD_heatsink_and_fan.jpg/330px-AMD_heatsink_and_fan.jpg",
    category: "Cooling",
    rating: 4.7,
    description: "360mm liquid cooler with quiet pump and customizable ARGB lighting.",
  },
  {
    name: "GlacierWind Tower Cooling",
    price: 84.99,
    originalPrice: null,
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e2/80mm_fan.jpg/330px-80mm_fan.jpg",
    category: "Cooling",
    rating: 4.6,
    description: "Dual-fan air cooler with high static pressure and low noise profile.",
  },
  {
    name: "Phantom Mesh Case",
    price: 139.99,
    originalPrice: null,
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/ca/Gabinete99.jpg/330px-Gabinete99.jpg",
    category: "Cases",
    rating: 4.6,
    description: "Mid-tower case with full mesh front panel and optimized airflow layout.",
  },
  {
    name: "Obsidian Glass Case",
    price: 199.99,
    originalPrice: 229.99,
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a4/Falcon_Northwest_Talon.png/330px-Falcon_Northwest_Talon.png",
    category: "Cases",
    rating: 4.7,
    description: "Premium full-tower case with tempered glass and cable management channels.",
  },
  {
    name: "AeroFlow Compact Case",
    price: 109.99,
    originalPrice: 129.99,
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/ca/Gabinete99.jpg/330px-Gabinete99.jpg",
    category: "Cases",
    rating: 4.5,
    description: "Compact mid-tower with high airflow front panel and easy cable routing.",
  },
  {
    name: "Crystal Edge Case",
    price: 179.99,
    originalPrice: 209.99,
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a4/Falcon_Northwest_Talon.png/330px-Falcon_Northwest_Talon.png",
    category: "Cases",
    rating: 4.8,
    description: "Tempered glass showcase case with clean layout and premium finishes.",
  },
  {
    name: "Stealth Mini-ITX Case",
    price: 129.99,
    originalPrice: null,
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/ca/Gabinete99.jpg/330px-Gabinete99.jpg",
    category: "Cases",
    rating: 4.4,
    description: "Small-form-factor ITX case built for quiet cooling and a minimal desk setup.",
  },
  {
    name: "Viper Pro Wireless Mouse",
    price: 99.99,
    originalPrice: null,
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/22/3-Tasten-Maus_Microsoft.jpg/330px-3-Tasten-Maus_Microsoft.jpg",
    category: "Mice",
    rating: 4.7,
    description: "Ultra-light wireless mouse with esports-grade latency and precision sensor.",
  },
  {
    name: "ArcStrike Ultra Mouse",
    price: 59.99,
    originalPrice: null,
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f9/Wireless-trackman-mouse.jpg/330px-Wireless-trackman-mouse.jpg",
    category: "Mice",
    rating: 4.5,
    description: "Ergonomic gaming mouse with programmable buttons and RGB side accents.",
  },
  {
    name: "PulseFire TKL Keyboard",
    price: 119.99,
    originalPrice: null,
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/97/Keyboard_Construction.JPG/330px-Keyboard_Construction.JPG",
    category: "Keyboards",
    rating: 4.7,
    description: "Tournament keyboard with linear switches and fast polling for FPS titles.",
  },
  {
    name: "Quantum 75 Keyboard",
    price: 149.99,
    originalPrice: null,
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e6/Typing_example.ogv/330px--Typing_example.ogv.jpg",
    category: "Keyboards",
    rating: 4.8,
    description: "Hot-swap 75% keyboard with gasket mount and per-key RGB customization.",
  },
  {
    name: "NovaView 55 4K TV",
    price: 699.99,
    originalPrice: 799.99,
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e2/LG_smart_TV.jpg/330px-LG_smart_TV.jpg",
    category: "TVs",
    rating: 4.6,
    description: "4K UHD gaming TV with low input lag, VRR support, and HDR performance.",
  },
  {
    name: "CinemaEdge 65 OLED TV",
    price: 1499.99,
    originalPrice: null,
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8f/Mirai_LCD_TV.JPG/330px-Mirai_LCD_TV.JPG",
    category: "TVs",
    rating: 4.9,
    description: "Premium OLED TV with deep contrast, 120Hz panel, and HDMI 2.1 features.",
  },
  {
    name: "Orbit X Console",
    price: 499.99,
    originalPrice: null,
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/77/Black_and_white_Playstation_5_base_edition_with_controller.png/330px-Black_and_white_Playstation_5_base_edition_with_controller.png",
    category: "Consoles",
    rating: 4.8,
    description: "Next-gen console with fast SSD loading and immersive 4K gameplay support.",
  },
  {
    name: "RetroBox S Console",
    price: 299.99,
    originalPrice: null,
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7e/PS4-Console-wDS4.jpg/330px-PS4-Console-wDS4.jpg",
    category: "Consoles",
    rating: 4.5,
    description: "Compact console built for casual gaming, streaming apps, and family play.",
  },
];

const categoryImages = {
  Controllers: "https://upload.wikimedia.org/wikipedia/commons/5/59/DualShock_4.jpg",
  Audio: "https://images.unsplash.com/photo-1599669454699-248893623440?w=1200&auto=format&fit=crop&q=80",
  Keyboards: "https://images.unsplash.com/photo-1618384887929-16ec33fab9ef?w=1200&auto=format&fit=crop&q=80",
  Mice: "https://images.unsplash.com/photo-1527814050087-3793815479db?w=1200&auto=format&fit=crop&q=80",
  Monitors: "https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?w=1200&auto=format&fit=crop&q=80",
  Accessories: "https://images.unsplash.com/photo-1616788494672-ec7ca25fdda9?w=1200&auto=format&fit=crop&q=80",
  Furniture: "https://images.unsplash.com/photo-1598550476439-6847785fcea6?w=1200&auto=format&fit=crop&q=80",
  GPUs: "https://upload.wikimedia.org/wikipedia/commons/d/df/Leistungsanalyse_NVIDIA_GeForce_RTX_4090_%28Geekerwan%29_02_cropped.jpg",
  CPUs: "https://upload.wikimedia.org/wikipedia/commons/0/0a/Intel_i9-14900KF_CPU.jpg",
  Cooling: "https://upload.wikimedia.org/wikipedia/commons/2/25/AMD_heatsink_and_fan.jpg",
  Cases: "https://upload.wikimedia.org/wikipedia/commons/c/ca/Gabinete99.jpg",
  TVs: "https://upload.wikimedia.org/wikipedia/commons/e/e2/LG_smart_TV.jpg",
  Consoles:
    "https://upload.wikimedia.org/wikipedia/commons/7/77/Black_and_white_Playstation_5_base_edition_with_controller.png",
};

const normalizedProducts = products.map((product) => ({
  ...product,
  image: categoryImages[product.category] ?? product.image,
}));

async function seed() {
  await connectDB();
  const ops = normalizedProducts.map((product) =>
    Product.findOneAndUpdate({ name: product.name }, product, {
      upsert: true,
      new: true,
      setDefaultsOnInsert: true,
    })
  );
  await Promise.all(ops);
  const count = await Product.countDocuments();
  console.log(`Seeded/updated ${products.length} products. Database now has ${count} products.`);
  process.exit(0);
}

seed().catch((err) => {
  console.error(err);
  process.exit(1);
});
